name: Run all tests
on: [push, pull-request]
jobs:
  run-all-tests:
    runs-on: unbuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with: 
        node-version: "14.x"

    - name: Install dependencies
      run: npm install

    - name: Run Jest
      run: npm run test
      
    - name: Run Eslint
      run: npm run lint
      
    - name: Run Prettier
      run: npm run check-format
